export const brands = {
  102: '10DAYS',
  111: '11 DEGREES',
  190: '1904',
  240: '24Bottles',
  270: '274',
  310: '3.1 Phillip Lim',
  880: '8848 Altitude',
  AF8: 'A fish named fred',
  APC: 'A\'PIEU',
  AK6: 'A.Kjærbede',
  AI1: 'A.S.98',
  AA3: 'Aaiko',
  A0F: 'Abercrombie & Fitch',
  ABD: 'Abhati Suisse',
  ABB: 'Abrand Jeans',
  AB2: 'Abro',
  AB3: 'Absorba',
  ACA: 'Active by Zizzi',
  ADC: 'Adele Dezotti',
  A0C: 'ADIA',
  ADID: 'adidas',
  AD7: 'adidas by Stella McCartney',
  ADE: 'Adidas Fragrance',
  TA4: 'adidas Golf',
  AD1: 'adidas Originals',
  AD5: 'adidas Performance',
  AD4: 'Adrianna Papell',
  AEF: 'aerie',
  AE9: 'Aeyde',
  AFA: 'Afends',
  '0AE': 'After Eden',
  AF9: 'AFTERMATH',
  AG0: 'AG Jeans',
  AG1: 'Agent Provocateur',
  AGA: 'Agolde',
  AI2: 'Aigle',
  '2AI': 'AIGNER',
  AF3: 'Alberta Ferretti',
  AZ7: 'Alberto Zago',
  AL00: 'ALDO',
  A01: 'ALDO',
  ALI: 'ALDO Wide Fit',
  ALK: 'Alessandro Zavetti',
  AL01: 'Alexander McQueen',
  '6AL': 'Alexander McQueen',
  AM9: 'Alice McCall',
  ALY: 'ALIGNE',
  ALV: 'all in',
  ALP: 'Allen Schwartz',
  A0Q: 'AllSaints',
  AL8: 'Alma en Pena',
  ALJ: 'ALOHAS',
  ALN: 'Alpe',
  ALG: 'Alpenflüstern',
  AL5: 'Alpha Industries',
  AL6: 'Alpina',
  AM4: 'American Eagle',
  AM2: 'American Vintage',
  AMT: 'AMICCI',
  AMW: 'amor',
  A44: 'Amor, Trust & Truth',
  AMH: 'AMOSTYLE',
  AMJ: 'AMOV',
  AMF: 'Amsterdenim',
  AN4: 'Anatomicals',
  AN01: 'Anaya with love',
  ANY: 'Anaya with love',
  A0W: 'Anaya with love Maternity',
  A0M: 'And Less',
  A30: 'Anderson\'s',
  A32: 'Andres Machado',
  ANQ: 'anello',
  A23: 'Anerkjendt',
  A0P: 'ANGULUS',
  A49: 'Anita',
  ANE: 'Ann Summers',
  A1E: 'ANNA ETTER',
  AN00: 'Anna Field',
  AN6: 'Anna Field',
  AX8: 'Anna Field Curvy',
  EX4: 'Anna Field MAMA',
  ANI: 'Anna Field Petite',
  AND: 'Anna Field Select',
  ANH: 'Anna Field Tall',
  ANJ: 'Anna Field Wide Fit',
  AN2: 'Anne Semonin',
  ANW: 'ANNY NORD',
  A0O: 'Another Influence',
  ANP: 'Another-Label',
  ANM: 'Anthony',
  A1A: 'Antipodes',
  ANG: 'Anton Heunis',
  A18: 'Antony Morato',
  '4AP': 'Apart',
  APD: 'APoem',
  AP2: 'Apple of Eden',
  A57: 'APRICOT',
  ARAJ: 'ara',
  AR2: 'ara',
  ARK: 'Aramis',
  ARJ: 'Ardell',
  A15: 'Arena',
  ARS: 'Argentum',
  ARU: 'ARKET',
  ARG: 'ARKK Copenhagen',
  ARMA: 'Armani',
  ARC: 'Armani Exchange',
  A22: 'Armor lux',
  AR8: 'Arnette',
  ARN: 'Art de Parfum',
  A07: 'ASCENO',
  AS2: 'Ash',
  ASF: 'Ashley Graham Lingerie by Addition Elle',
  AS00: 'Asics',
  AS1: 'ASICS',
  A0H: 'ASICS SportStyle',
  ASH: 'ASRA',
  ASE: 'Astrid & Miyu',
  ATD: 'ATTESA',
  AUH: 'Augustinus Bader',
  AU0: 'Automobili Lamborghini Kidswear',
  AV9: 'Aveda',
  AZ00: 'Azzaro',
  AZ1: 'Azzaro',
  AZ8: 'Azzaro Parfums',
  AEI: 'AÉROPOSTALE',
  AED: 'Aéryne',
  BFA: 'B FNKY',
  BYK: 'B YOGA',
  BT7: 'b.belt',
  BY2: 'b.young',
  BAU: 'BABY-G',
  B1I: 'Badger',
  BAM: 'BadRhino',
  B1H: 'Bag N Noun',
  B2T: 'Bahe',
  BA7: 'Baldessarini',
  B1N: 'Balloon',
  '23B': 'Bally',
  B1E: 'Bama',
  B2H: 'Bamboo Basics',
  B35: 'Banana Moon',
  BA03: 'Banana Republic',
  BJ7: 'Banana Republic',
  B3E: 'Banana Republic Petite',
  B1X: 'Banana Republic Tall',
  B2G: 'Banila Co',
  BAW: 'Barbara Lebek',
  BAY: 'Barber Pro',
  B1G: 'Barberians',
  BARB: 'Barbour',
  BA2: 'Barbour',
  B1K: 'Barbour Beacon',
  BG8: 'Barbour International',
  BA01: 'Bardot',
  B0M: 'Bardot',
  BAK: 'Bardot Junior',
  BK5: 'Barker',
  B89: 'Barts',
  BA1: 'Base London',
  B1D: 'Baxter of California',
  B3R: 'BAYTON',
  BLN: 'BBB London',
  MX1: 'BCBGMAXAZRIA',
  QX7: 'BDG Urban Outfitters',
  ED0: 'Be Edgy',
  B0I: 'Be Natural',
  B30: 'Be Only',
  BET: 'Beauugreen',
  BEF: 'BEBO',
  BEU: 'Bec & Bridge',
  B12: 'Becksöndergaard',
  B70: 'Bellfield',
  B3F: 'Belly Bandit',
  BE8: 'bellybutton',
  BE9: 'Belstaff',
  B2M: 'BeMammy',
  BESH: 'Ben Sherman',
  BE1: 'Ben Sherman',
  BT5: 'Ben Sherman Tailoring',
  BES: 'Benamor',
  BE6: 'Bench',
  '4BE': 'Benetton',
  BEP: 'Benton',
  BN6: 'Bergans',
  RG6: 'Bergstein',
  BEA: 'Bernie Mev',
  BEO: 'Berrisom',
  BEJ: 'Bershka',
  B01: 'Bertoni',
  BEX: 'Best Company',
  B0N: 'Betty & Co',
  BEV: 'Beyer\'s Oil',
  BID: 'Bianca Di',
  BI00: 'Bianco',
  BJ0: 'Bianco',
  BIN: 'Bianco Wide Fit',
  BK7: 'Bickley+Mitchell',
  BIJ: 'BIDI BADU',
  '6BI': 'Bikkembergs',
  BI7: 'Billabong',
  BI6: 'Billi Bi',
  BH5: 'Billieblush',
  BIA: 'Billybandit',
  BIQ: 'Biolage',
  BIP: 'Bioworld',
  BIO: 'Birgitte Herskind',
  BIRK: 'Birkenstock',
  BI1: 'Birkenstock',
  BIU: 'Birkenstock Cosmetics',
  BI4: 'Birkis',
  B58: 'Bisgaard',
  BJ2: 'Björn Borg',
  BLF: 'Black Diamond',
  BL7: 'Blackstone',
  BLW: 'BLANCHE',
  BM9: 'Blauer',
  BL5: 'Blend',
  BLR: 'Blendshe',
  BLS: 'Blind Barber',
  B36: 'Bloch',
  BB7: 'Blood Brother',
  BL1: 'Blowfish Malibu',
  BLJ: 'Blue by Betsey Johnson',
  BE0: 'Blue Effect',
  B2D: 'Blue Heeler',
  BL8: 'Blue Seven',
  BZ3: 'Bluebella',
  BS9: 'Blundstone',
  B69: 'Boboli',
  BOGN: 'Bogner',
  BO7: 'Bogner',
  F22: 'Bogner Fire + Ice',
  B73: 'Bogs',
  BOM: 'Bolzr',
  B3C: 'Bombay Sunset',
  OM3: 'Bombers',
  BO6: 'Bomboogie',
  BON: 'Bonds',
  BX3: 'Boob',
  B2W: 'Boscia',
  BB1: 'BOSS',
  BO1: 'BOSS CASUAL',
  BO9: 'BOSS Kidswear',
  BOF: 'Boux Avenue',
  BO2: 'Boxfresh',
  BOU: 'Boyish',
  BRM: 'Brandit',
  B1T: 'Brava Fabrics',
  BRT: 'Bravado Designs',
  BRH: 'Brave Soul',
  B38: 'Bree',
  BR00: 'Brenda Zaro',
  BZ0: 'Brenda Zaro',
  BRN: 'Brenda Zaro Wide Fit',
  BS3: 'Brett & Sons',
  BRQ: 'Bricktown',
  B24: 'British Knights',
  BX9: 'Brixtol Textiles',
  B51: 'Brixton',
  BR1: 'Bronx',
  BRL: 'Brooklyn Soap',
  BP9: 'Brooklyn Supply Co.',
  BR01: 'Bruno Banani',
  '1BR': 'Bruno Banani',
  BRR: 'Bruno Banani Fragrance',
  BR7: 'Bruno Premi',
  B32: 'Brunotti',
  BRI: 'Bruun & Stengade',
  BR3: 'Bruuns Bazaar',
  B43: 'Buff',
  BU00: 'Buffalo',
  BU3: 'Buffalo',
  BUB: 'Buffalo London',
  BU1: 'Bugatti',
  BU2: 'Bullboxer',
  BUF: 'Bumble and bumble',
  BU7: 'Burberry',
  BU4: 'Burlington',
  BU5: 'Burt\'s Bees',
  B17: 'Burton',
  M08: 'Burton Menswear London',
  BYF: 'BY GARMENT MAKERS',
  BY1: 'By Malene Birger',
  BYC: 'By Malina',
  BYI: 'by-bar',
  BYB: 'BYBI',
  BYH: 'byTiMo',
  C08: 'C.P. Company',
  CA2: 'Ca\'Shott',
  C4K: 'Cacharel Fragrance',
  CZ0: 'Cache Coeur',
  CA7: 'CAFèNOIR',
  CAU: 'Cake Maternity',
  C54: 'CALANDO',
  CF7: 'Calida',
  AX9: 'Call it Spring',
  C2D: 'Call It Spring Wide Fit',
  CAW: 'Callaway',
  CALV: 'Calvin Klein',
  '6CA': 'Calvin Klein',
  C4P: 'Calvin Klein Fragrances',
  CK4: 'Calvin Klein Golf',
  C18: 'Calvin Klein Jeans',
  C2Q: 'Calvin Klein Jeans Plus',
  CKA: 'Calvin Klein Performance',
  C17: 'Calvin Klein Swimwear',
  CAR: 'Calvin Klein Tailored',
  C11: 'Calvin Klein Underwear',
  C4J: 'Calzitaly',
  C51: 'camano',
  CA3: 'Camper',
  CD0: 'Canadian Classics',
  CA8: 'Candice Cooper',
  C3J: 'Capezio',
  C75: 'Capo',
  CA4: 'Caprice',
  CAS: 'CAPSULE by Simply Be',
  C14: 'Carhartt WIP',
  CW2: 'Carin Wester',
  CAP: 'Carlo Colucci',
  CAL: 'Carmela',
  C3X: 'carpatree',
  C0V: 'Carrement Beau',
  CA00: 'Carrera',
  '14C': 'Carrera',
  C2U: 'Carrera Footwear',
  C4D: 'Carrera Jeans',
  C74: 'Cars Jeans',
  CJ2: 'Carter\'s',
  C04: 'Cartoon',
  C61: 'Carvela',
  CAN: 'Carvela Comfort',
  C3D: 'Casa Amuk',
  C73: 'Casadei',
  C44: 'Casall',
  C15: 'Casio',
  C5E: 'Cassis',
  CA6: 'Castañer',
  C1A: 'Casual Friday',
  CA01: 'CAT Footwear',
  CA1: 'Cat Footwear',
  C2K: 'Caterpillar',
  CA02: 'Cath Kidston',
  CZ8: 'Cath Kidston',
  C3W: 'Cath Kidston Beauty',
  C27: 'Catimini',
  CS6: 'Cayler & Sons',
  CCB: 'CC COLLECTION CORNELIANI',
  '5CC': 'Ceceba',
  CEC: 'CECILIE copenhagen',
  CV3: 'CeLaVi',
  CF5: 'CELIO',
  CED: 'Cellu-Cup',
  C3L: 'Chaco',
  CHQ: 'Chalmers',
  CH00: 'Champion',
  C76: 'Champion',
  C0T: 'Champion Reverse Weave',
  C4A: 'Champion Rochester',
  '5CH': 'Chantal Thomass',
  CH9: 'Chantelle',
  CZ5: 'CHASIN\'',
  CHU: 'Chatelles',
  CH6: 'Cheap Monday',
  CF9: 'Chelsea Peers',
  CH01: 'Chi Chi',
  CHT: 'Chi Chi Girls',
  CZ6: 'Chi Chi London',
  CV7: 'Chi Chi London Curvy',
  C2M: 'Chi Chi London Maternity',
  CHD: 'Chi Chi London Petite',
  CHC: 'Chi Chi London Tall',
  C3C: 'Chi Modu',
  CHV: 'CHIARA FERRAGNI',
  CH2: 'Chie Mihara',
  C38: 'Chiemsee',
  C96: 'Chillouts',
  CHZ: 'CHiMi',
  CHO: 'CHINTI & PARKER',
  C4O: 'Chio',
  CH3: 'Chipie',
  CHW: 'Chipmunks',
  '1CH': 'Chloé',
  CW9: 'CHPO',
  CX5: 'CHRIST',
  CHM: 'Christophe Robin',
  CID: 'CIA MARÍTIMA',
  CIH: 'Cigit',
  CI1: 'Cinque',
  CII: 'Circular&Co',
  CI4: 'Ciso',
  CT9: 'Citizen',
  CI2: 'Citizens of Humanity',
  CIA: 'City Chic',
  CK1: 'CK Calvin Klein',
  CL2: 'Clae',
  CL8: 'Claesen‘s',
  CLAR: 'Clarks',
  CL1: 'Clarks',
  CL6: 'Clarks Originals',
  CLI: 'Clarks Unstructured',
  CLE: 'Classics77',
  CLA: 'Claudie Pierlot',
  CLB: 'Cleptomanicx',
  CX4: 'clic!',
  CL01: 'Clinique',
  CLL: 'Clinique',
  CLP: 'Clinique for Men',
  CL3: 'CLOSED',
  CL9: 'Closet',
  CLR: 'CLOSURE London',
  CLS: 'Cloudsteppers by Clarks',
  CLK: 'Club L London',
  C0K: 'Club Monaco',
  CLO: 'Clubman Pinaud',
  C0N: 'Cluse',
  CQ4: 'CMEO COLLECTIVE',
  C70: 'CMP',
  CO03: 'co wren',
  C1S: 'co wren',
  C1T: 'co wren wide fit',
  COH: 'Coach',
  CO3: 'Coccinelle',
  C1O: 'Coco & Eve',
  C3R: 'Coco de Mer',
  CO9: 'Codello',
  CZ4: 'Cole Haan',
  C3N: 'Collectif',
  C1W: 'Collistar',
  COLM: 'Colmar',
  C00: 'Colmar',
  CM0: 'Colmar Originals',
  '1CK': 'Color Kids',
  C3Z: 'COLOR WOW',
  CO6: 'Colors of California',
  C5J: 'Colourful Rebel',
  CLC: 'COLOURWEAR',
  C23: 'Columbia',
  CO01: 'comma',
  CO1: 'comma',
  C1E: 'comma casual identity',
  C2R: 'COMME DEUX',
  C2V: 'Common Kollectiv',
  C20: 'Compagnie de Provence',
  C3S: 'CONSIGNED',
  CO4: 'Converse',
  C30: 'Coolway',
  COY: 'Copenhagen',
  C3A: 'Copenhagen Muse',
  C2X: 'Copenhagen Shoes',
  C0H: 'Cordwainer',
  C2N: 'CORELLA',
  CO02: 'CORNELIANI',
  COP: 'CORNELIANI',
  CZ9: 'Cortefiel',
  C47: 'Cosabella',
  CK8: 'Cosmoparis',
  COS: 'COSRX',
  CZ2: 'Cost:bart',
  CO04: 'Cotton On',
  C1Q: 'Cotton On',
  C1R: 'Cotton On Body',
  C1V: 'Cotton On Curve',
  C2C: 'Courreges',
  C66: 'Craft',
  '3CR': 'Craghoppers',
  CRG: 'Cras',
  CR2: 'Cream',
  CRM: 'CREAM BEAR',
  '9CL': 'Crime London',
  CN9: 'Criminal Damage',
  CR4: 'Crocs',
  CR8: 'Cross Sportswear',
  CR9: 'Cruyff',
  CU2: 'Culture',
  CUH: 'Curaprox',
  CY5: 'Curare Yogawear',
  CU0: 'Current/Elliott',
  C0Q: 'Curvy Kate',
  CU7: 'Custommade',
  C0M: 'Cyberjammies',
  CY1: 'Cyell',
  D0C: 'D-STRUCT',
  DX2: 'D-XEL',
  DAR: 'Daily Basis Studios',
  DAM: 'Daily Sports',
  DA7: 'Dakine',
  DD4: 'Damir Doma',
  DAI: 'Danefæ København',
  DA8: 'Daniel Hechter',
  DAH: 'Daniel Sandler',
  DW2: 'Daniel Wellington',
  D18: 'Dare 2B',
  D08: 'Darkwood',
  DAO: 'Darphin',
  D0T: 'David Koma',
  DAP: 'Davida Cashmere',
  D0P: 'DAVIDOFF Fragrances',
  DA3: 'DAY Birger et Mikkelsen',
  DAT: 'DAY ET',
  DAN: 'Day Time',
  DC1: 'DC Shoes',
  DEH: 'DE LILOU',
  D1E: 'Dea Kudibal',
  D0U: 'Deadwood',
  DEW: 'Dear Denier',
  DEQ: 'Decadent Copenhagen',
  D0N: 'DECHASE',
  '4DE': 'Decoy',
  DEL: 'Dedicated',
  DE01: 'DeFacto',
  DEZ: 'DeFacto',
  D1G: 'DeFacto Fit',
  '5DE': 'Deha',
  DL7: 'Delicatelove',
  DEI: 'delilah',
  DE4: 'Denham',
  DH5: 'Denim Hunter',
  DEO: 'Denim Project',
  DE3: 'DEPECHE',
  DEM: 'Depp',
  DE8: 'Derbe',
  D35: 'Derbystar',
  RD5: 'Derhy',
  DEN: 'Derhy Kids',
  DEA: 'DESIGNERS REMIX',
  DE1: 'Desigual',
  DS8: 'Desires',
  D47: 'Deuter',
  DEU: 'Devoted By Zizzi',
  DH6: 'DHC',
  D29: 'Diadora',
  DID: 'DIAMANT L\'ÉTERNEL',
  DIG: 'Diamond Supply Co.',
  DF2: 'Diane von Furstenberg',
  DI6: 'Dickies',
  DI5: 'Didriksons',
  DIES: 'Diesel',
  DI1: 'Diesel',
  DIU: 'Diesel Fragrance',
  DIM: 'DillySocks',
  DM1: 'DIM',
  DF5: 'Divine Factory',
  DJ1: 'Djinn\'s',
  DK00: 'DKNY',
  DK1: 'DKNY',
  DK9: 'DKNY Fragrance',
  '1DK': 'DKNY Intimates',
  DLA: 'DL Sport',
  DL4: 'DL1961',
  DOL: 'dobell',
  DO8: 'DOCKERS',
  DO1: 'Dockers by Gerli',
  DOJ: 'Doers of London',
  DV4: 'Dolce Vita',
  DO7: 'Dolce&Gabbana',
  '3DD': 'Dondup',
  DO3: 'Donna Carolina',
  DOC: 'Dora Larsen',
  DO01: 'DORINA',
  DOG: 'DORINA',
  DOH: 'DORINA CURVES',
  DO00: 'Dorothy Perkins',
  DP5: 'Dorothy Perkins',
  DP6: 'Dorothy Perkins Curve',
  DP8: 'Dorothy Perkins Maternity',
  DP7: 'Dorothy Perkins Petite',
  DOA: 'Dorothy Perkins Tall',
  DOB: 'Dorothy Perkins Wide Fit',
  DOR: 'Double Cross',
  DO4: 'Doucal\'s',
  D0E: 'Doughnut',
  DRK: 'Dr Botanicals',
  DRG: 'Dr Dennis Gross',
  DRF: 'Dr. Bronner´s',
  DRO: 'Dr. Fatemi Skincare',
  DRR: 'Dr. Kerklaan',
  DRS: 'Dr. Lipp',
  DO2: 'Dr. Martens',
  DRH: 'Dr. PAWPAW',
  DR00: 'Dr.Denim',
  DR1: 'Dr.Denim',
  DRC: 'Dr.Denim Petite',
  DRQ: 'Dr.Denim Plus',
  DRD: 'Dr.Denim Tall',
  DRJ: 'Dranella',
  '4DR': 'DreiMaster',
  DRB: 'Drumohr',
  DR2: 'DRYKORN',
  DT4: 'Dstrezzed',
  DU00: 'DUNE LONDON',
  DU5: 'Dune London',
  DUB: 'Dune London WIDE FIT',
  DUN: 'Dunhill',
  DUF: 'DUO',
  DUA: 'Duvetica',
  DY0: 'Dynafit',
  DY3: 'Dyrberg/Kern',
  D24: 'Döll',
  E80: 'E8 BY MIISTA',
  EA7: 'EA7 Emporio Armani',
  E09: 'Eastland',
  EA2: 'Eastpak',
  EAD: 'Easy Livin\'',
  EP1: 'Easy Peasy',
  EB9: 'Ebbe',
  EC1: 'ECCO',
  ECE: 'Echo Design',
  ECA: 'Eco by Sonya',
  ECD: 'Ecoalf',
  ED2: 'Ed Hardy',
  ED1: 'edc by Esprit',
  EDE: 'EDC Petite',
  EDB: 'EDIFICE',
  EDD: 'EDITED',
  EDA: 'Editions MR',
  ED3: 'Edwin',
  EG3: 'EGO',
  EG2: 'Egyptian Magic',
  EI2: 'Eisbär',
  EI0: 'Eivy',
  EL1: 'El Naturalista',
  EE1: 'Elefanten',
  EL8: 'Element',
  EL4: 'Elemental Herbology',
  EF1: 'Elisabetta Franchi',
  ELI: 'Elixr',
  EL7: 'Elizabeth Arden',
  EL9: 'Ellesse',
  EL0: 'Elli',
  ELD: 'ELLIS FAAS',
  E07: 'Elomi',
  ELA: 'else',
  EL3: 'Elvine',
  '2EP': 'Emilio Pucci',
  EV8: 'Emily van den Bergh',
  EMD: 'Emma Hardie',
  EMJ: 'Emmshu',
  EA8: 'Emporio Armani',
  EMA: 'Emporio Armani Connected',
  EM1: 'EMU Australia',
  END: 'Endurance',
  EN6: 'Enter',
  EF3: 'Envie de Fraise',
  EI4: 'Envii',
  EO0: 'EOE Eyewear',
  ER7: 'ERASE',
  ER9: 'Ere Perez',
  '1ER': 'Erima',
  ESCA: 'Escada',
  E21: 'Escada',
  ESO: 'Escada Fragrances',
  E16: 'Escada Sport',
  ESJ: 'esmé studios',
  ES2: 'Espadrij l´originale',
  ESPR: 'Esprit',
  ES1: 'Esprit',
  ES4: 'Esprit Collection',
  ESK: 'Esprit Collection Petite',
  ES9: 'Esprit Maternity',
  ESI: 'Esprit Petite',
  ESM: 'Esqualo',
  E40: 'Essie',
  ESG: 'Estelle & Thild',
  ESD: 'Estée Lauder',
  ET9: 'Etam',
  '2ET': 'Eterna',
  ET1: 'Etnies',
  ET8: 'Eton',
  ETB: 'ETQ',
  EW2: 'Evans',
  EV00: 'Even&Odd',
  EV4: 'Even&Odd',
  EV9: 'Even&Odd active',
  EVB: 'Even&Odd Curvy',
  EVF: 'Even&Odd Petite',
  EVI: 'Even&Odd Tall',
  EVC: 'Even&Odd Wide Fit',
  '2EV': 'Everlast',
  EV2: 'Everybody',
  EVJ: 'Everyday Hero',
  EV6: 'Evita',
  EW3: 'Ewers',
  EW0: 'Ewing',
  EXC: 'Expatrié',
  EX1: 'Expresso',
  EY0: 'Eyeko',
  FW0: 'F_WD',
  FAH: 'Fabienne Chapot',
  F0N: 'Fable & Eve',
  FA0: 'Fabrizio',
  FAZ: 'Face Halo',
  FAQ: 'FACE STOCKHOLM',
  FA7: 'Faguo',
  FAB: 'faina',
  FAK: 'Faith Wide Fit',
  FAT: 'FAKTOR',
  FA1: 'FALKE',
  F0Q: 'Family First',
  FAV: 'Fanatics',
  FN1: 'Fantasie',
  FARA: 'Farah',
  FA5: 'Farah',
  FAI: 'Farah Tailoring',
  F0I: 'Farm Rio',
  FA01: 'Fashion Union',
  FAA: 'Fashion Union',
  FAE: 'Fashion Union Petite',
  FAJ: 'Fashion Union Plus',
  FAC: 'Fashion Union Tall',
  FEG: 'Fedua',
  FEA: 'Felipa',
  FE00: 'Felmini',
  FE2: 'Felmini',
  FEF: 'Felmini Wide Fit',
  FEJ: 'Fertini',
  FI00: 'Fila',
  '1FI': 'Fila',
  FID: 'Fila Petite',
  FIQ: 'Fila Plus',
  FIE: 'Fila Tall',
  F14: 'Filippa K',
  F16: 'Filson',
  FIJ: 'fine',
  F42: 'Finkid',
  F06: 'Fiore di Lucia Milano',
  FI9: 'Fiorucci',
  F0P: 'Fire & Glory',
  FIK: 'FIRST',
  FI3: 'FitFlop',
  FIG: 'Fitters',
  FU8: 'Fiveunits',
  FLH: 'Flamingos\' Life',
  FLJ: 'Flaxta',
  FF0: 'Flexfit',
  FLC: 'Flik Flak',
  FL1: 'flip*flop',
  FLL: 'FLORENCE BRIDGE',
  FL4: 'Floris van Bommel',
  FL3: 'Florsheim',
  FL2: 'Fly London',
  FO0: 'Folk',
  FOF: 'FoR',
  FOI: 'Foreo',
  FOG: 'Forever Fit',
  FO01: 'Forever New',
  FOD: 'Forever New',
  FOP: 'Forever New Curve',
  FOJ: 'Forever New Petite',
  FO02: 'Forever Unique',
  '4FU': 'Forever Unique',
  FOQ: 'forét',
  FO00: 'Fossil',
  FS1: 'Fossil',
  FOA: 'Fossil Smartwatches',
  FO4: 'Fox Racing',
  FOH: 'Foxiedox',
  F53: 'Fraas',
  FD5: 'Frame Denim',
  F10: 'Frank Wright',
  FR3: 'Franklin & Marshall',
  F21: 'Fransa',
  F15: 'Fratelli Rossetti',
  FRI: 'Fratelli Russo',
  '1FN': 'Freaky Nation',
  FR2: 'Fred de la Bretoniere',
  F0E: 'Fred\'s World by GREEN COTTON',
  FR7: 'FREDsBRUDER',
  FP0: 'Free People',
  '6FR': 'Freeman T. Porter',
  F08: 'Freequent',
  FR6: 'French Connection',
  FRO: 'French Girl',
  F56: 'Frends',
  FRL: 'Frescobol Carioca',
  FRG: 'Fresh \'n Rebel',
  FR5: 'Fretz Men',
  FR9: 'Freya',
  F57: 'Friboo',
  FF2: 'Frieda & Freddies',
  F11: 'Fritzi aus Preußen',
  F01: 'Froddo',
  F09: 'Frugi',
  FT2: 'FTC Cashmere',
  FU4: 'FUBU',
  FUD: 'FUCHS SCHMITT',
  FU0: 'Fudge',
  FU1: 'Furla',
  '7FL': 'Fusalp',
  GF3: 'G-Form',
  GS9: 'G-SHOCK',
  GS1: 'G-Star',
  G90: 'G9',
  G50: 'Gabba',
  GAM: 'Gabbiano',
  GA01: 'Gabor',
  GA1: 'Gabor',
  GAJ: 'Gabor Comfort',
  G11: 'Gabriele',
  GA4: 'Gadea',
  GAK: 'GAI+LISVA',
  GAL: 'Gaimo',
  GA3: 'GANT',
  GAP: 'Ganter',
  GA00: 'gap',
  GP0: 'GAP',
  G0F: 'GAP Maternity',
  GAG: 'GAP Petite',
  GAH: 'Gap Tall',
  GA2: 'Gardenia',
  GAC: 'GARMENT PROJECT',
  GF2: 'GAS Footwear',
  GC9: 'GCDS',
  GEC: 'Gebe',
  GEI: 'Genesis',
  G0H: 'Genuins',
  GE1: 'Geox',
  GERR: 'Gerry Weber',
  GW1: 'Gerry Weber',
  GEF: 'Gerry Weber Casual',
  GE2: 'Gestuz',
  GH4: 'Ghost',
  GIG: 'Gianni Kavanagh',
  GIH: 'Gianni Lupo',
  GI1: 'Giesswein',
  GIB: 'Gilly Hicks',
  GI00: 'Gina Tricot',
  GID: 'Gina Tricot',
  GIL: 'Gina Tricot Petite',
  G01: 'Gino Rossi',
  G78: 'Giorgio 1958',
  G52: 'Gioseppo',
  GI2: 'Gipsy',
  GI9: 'Giro',
  GLH: 'Glamglow',
  GL00: 'Glamorous',
  GL9: 'Glamorous',
  GLI: 'Glamorous Bloom',
  GLA: 'Glamorous Curve',
  GLB: 'Glamorous Petite',
  GLC: 'Glamorous Tall',
  GLG: 'Glamorous Wide Fit',
  GLM: 'Glimyu',
  GL5: 'Globe',
  GLE: 'Glorious Gangsta',
  GLF: 'Glov',
  GL7: 'Gloverall',
  GLJ: 'GlowCup',
  GLK: 'GLOWE',
  GO1: 'Gola',
  GOK: 'Golden Beards',
  GOJ: 'Golden Equation',
  GT1: 'Goliath',
  GOM: 'Good American',
  GOG: 'Good For Nothing',
  GON: 'Good News',
  GOS: 'GOODBOIS',
  GOT: 'Goorin Bros',
  GO2: 'Goosecraft',
  GOD: 'Gore Wear',
  GOH: 'Gosh Copenhagen',
  GOF: 'Gosoaky',
  G53: 'Gossard',
  GOX: 'Got Bag',
  GOQ: 'Gottex',
  G0A: 'Grace',
  GRL: 'Gramicci',
  GR3: 'Grand Step Shoes',
  GRN: 'Great British Designer Face Coverings',
  GR9: 'Great Plains London',
  GRR: 'Green + The Gent',
  G17: 'Grenson',
  GRD: 'Grimey',
  GRE: 'GRO',
  GRC: 'Grounded',
  GRJ: 'Grow Gorgeous',
  GRO: 'Grown Alchemist',
  GRF: 'Grunt',
  GT0: 'GTA',
  GU4: 'Gucci',
  GU1: 'Guess',
  GUG: 'Gusti Leder',
  GY3: 'Gym King',
  HA2: 'H by Hudson',
  '4HI': 'H.I.S',
  HZ1: 'H2O Fagerholt',
  H0R: 'Haan',
  ASB: 'Hackett Aston Martin Racing',
  HA00: 'Hackett London',
  HT6: 'Hackett London',
  H27: 'Haglöfs',
  HA7: 'Halti',
  HK0: 'Han Kjøbenhavn',
  '2HA': 'Hanro',
  HAS: 'Hanz De Fuko',
  H1G: 'Hape',
  HG2: 'happy girls',
  HAB: 'Happy Plugs',
  HA01: 'Happy Socks',
  HA3: 'Happy Socks',
  HD1: 'Harley Davidson',
  HA4: 'HARRINGTON',
  H0L: 'Hash#TAG Sustainable',
  HAE: 'HASSIA',
  H21: 'Hatley',
  HAL: 'Haute Custom Beauty',
  HA1: 'Havaianas',
  HE7: 'Head',
  H05: 'Head over Heels by Dune',
  '2HE': 'Heideman',
  HK4: 'Heidi Klum Intimates',
  HEH: 'Hej Organic',
  HE6: 'Helly Hansen',
  HEN: 'Henrik Vibskov',
  HEM: 'Hermina Athens',
  '4HE': 'Herrlicher',
  H15: 'Herschel',
  HL4: 'Hervé Léger',
  HED: 'Hesper Fox',
  H1P: 'Hexeline',
  H0J: 'Hey Honey',
  HI2: 'Hi-Tec',
  HIB: 'Hickies',
  HIF: 'Hide&Jack',
  HI8: 'HIIT',
  HI7: 'Hikari',
  HI1: 'Hilfiger Denim',
  HID: 'Hill & Friends',
  HI3: 'Hip',
  HI9: 'Hispanitas',
  HK6: 'HKT by Hackett',
  HB8: 'Hobbs',
  '0HC': 'Hofmann Copenhagen',
  H0X: 'Holika Holika',
  H04: 'Hollister Co.',
  HO0: 'Holzweiler',
  H0K: 'HOMEBASE',
  H14: 'Homeboy',
  HO3: 'Homers',
  HOP: 'Honey Punch',
  H0Y: 'Hoodrich',
  H42: 'Hope',
  HO00: 'Hope & Ivy',
  HOT: 'Hope & Ivy',
  HON: 'Hope & Ivy Maternity',
  HOL: 'Hope & Ivy Petite',
  HOM: 'Hope & Ivy Tall',
  HOX: 'HOSBJERG',
  HOH: 'Hot Soles',
  HOW: 'HotSquash',
  HOO: 'Houdini',
  HOU: 'HOUSE 99 by David Beckham',
  DG2: 'House of Dagmar',
  HOS: 'House of Holland',
  HU4: 'HUB',
  HUDS: 'Hudson',
  '4HU': 'Hudson',
  HUC: 'Hudson London',
  H0H: 'HUF',
  HU7: 'HUGO',
  BOSS: 'Hugo Boss',
  HU00: 'Hummel',
  HU3: 'Hummel',
  HUD: 'Hummel Hive',
  HM1: 'Hunkemöller',
  HU1: 'Hunter ORIGINAL',
  HU8: 'Hurley',
  HU9: 'Hush Puppies',
  HC3: 'Hust & Claire',
  H20: 'Huttelihut',
  HUF: 'Huxley',
  HV2: 'HVISK',
  HX0: 'HXTN Supply',
  HY5: 'Hype',
  HY9: 'Hysteria by Happy Socks',
  HU2: 'Högl',
  IW0: 'I WANT YOU NAKED',
  IA0: 'i.am+',
  IS6: 'I.scenery',
  '21B': 'Ibana',
  IB0: 'iBlues',
  IC9: 'Ice Watch',
  IC3: 'Iceberg',
  IC6: 'ICEBOUND',
  CE6: 'Icebreaker',
  IC1: 'Icepeak',
  IC2: 'ICHI',
  ICG: 'ICHI PETITE',
  CB9: 'Icon Brand',
  ICA: 'Icon Eyewear',
  ICB: 'Icon Sport',
  ID2: 'ID Fine',
  ID1: 'iDeal of Sweden',
  ID5: 'IDUN Minerals',
  GC1: 'IGI&CO',
  IG2: 'IGOR',
  JK2: 'IKKS',
  IL4: 'ILC',
  IL0: 'Illamasqua',
  IL1: 'Ilse Jacobsen',
  INM: 'INARI Arctic Beauty',
  INJ: 'INC.redible',
  IJ0: 'INDICODE JEANS',
  INO: 'Indiska',
  INE: 'Indispensable',
  IN8: 'Inov-8',
  NU5: 'Inuovo',
  INF: 'Invisibobble',
  IN3: 'InWear',
  IN7: 'Inyati',
  N19: 'ION',
  IP1: 'Ipanema',
  IR5: 'Irise Paris',
  IR2: 'Iro',
  DH0: 'Isaac Dewhirst',
  IS5: 'Isla Ibiza Bonita',
  IT2: 'it\'s skin',
  '5TE': 'ITEM m6',
  VK1: 'Ivko',
  IV00: 'Ivy & Oak',
  IV3: 'IVY & OAK',
  IV5: 'IVY & OAK BRIDAL',
  IV7: 'IVY & OAK Maternity',
  IV6: 'Ivy Copenhagen',
  IV4: 'Ivyrevel',
  IZ0: 'IZIA',
  IZ1: 'IZOD',
  IZ2: 'Izola',
  JB2: 'J Brand',
  JC00: 'J.CREW',
  JC4: 'J.CREW',
  JC5: 'J.CREW PETITE',
  JC6: 'J.CREW TALL',
  JL1: 'J.LINDEBERG',
  JAH: 'Jacamo',
  JACK: 'Jack & Jones',
  JA2: 'Jack & Jones',
  JAS: 'JACK & JONES Fragrances',
  JAN: 'Jack & Jones Junior',
  JAT: 'Jack & Jones Performance',
  JAM: 'Jack & Jones PREMIUM',
  J0C: 'Jack Black',
  JA4: 'Jack Wolfskin',
  JAJ: 'JACKS beauty line',
  J48: 'Jacky Baby',
  JAL: 'Jack´s Sportswear',
  JL0: 'Jaded London',
  J0G: 'Jadyn B',
  J32: 'JAKO',
  J44: 'James Perse',
  JAI: 'James Read',
  JA3: 'Jana',
  JA7: 'Janet Sport',
  J31: 'Jarlo',
  JAU: 'Jascha Stockholm',
  JBA: 'JBS',
  '2JC': 'JCC',
  JY1: 'JDY',
  JP0: 'Jeepers Peepers',
  JW1: 'Jeffery West',
  JE7: 'Jeffrey Campbell',
  JEF: 'Jellycat',
  JE5: 'Jenny',
  JEJ: 'Jerelyn Creado',
  JEC: 'JETS Australia',
  JE3: 'JETTE',
  JEE: 'Jette Fragrances',
  JI9: 'Jil Sander Fragrances',
  JI1: 'Jim Rickey',
  JI5: 'Jimmy Choo',
  JI4: 'Jimmy Lion',
  JO7: 'Jo Ghost',
  '5JO': 'Jockey',
  JOS: 'Joe\'s Jeans',
  JH1: 'Joha',
  JOJ: 'John Richmond',
  JOM: 'Johnny Urban',
  J23: 'Johnstons of Elgin',
  J26: 'JoJo Maman Bébé',
  J33: 'Joma',
  J21: 'Jonak',
  JOOP: 'Joop!',
  JO9: 'JOOP!',
  J14: 'Joop! Accessories',
  JOX: 'JOOP! Fragrances',
  JOG: 'JOOP! Jeans',
  JOC: 'Jordan',
  JOP: 'Jorgobé',
  JO1: 'Josef Seibel',
  JE0: 'Joseph',
  JOB: 'Josephine & Co',
  JOF: 'Joshua Sanders',
  JO5: 'Jost',
  J35: 'Jottum',
  JU7: 'Juicy Couture',
  JUG: 'Julie Sandlau',
  JR4: 'JUNAROSE - by VERO MODA',
  JU2: 'Junk De Luxe',
  JU6: 'Just Cavalli',
  JU1: 'JUST FEMALE',
  J04: 'Just Junkies',
  JUJ: 'JUTELAUNE',
  KG0: 'K-Glo',
  KS1: 'K-SWISS',
  KW1: 'K-Way',
  KA02: 'Kaffe',
  KA3: 'Kaffe',
  KAN: 'Kaffe Curve',
  K0G: 'Kaltur',
  KA6: 'Kamik',
  KA1: 'KangaROOS',
  K39: 'Kangol',
  K45: 'Kanna',
  KAI: 'Kaotiko',
  K20: 'Kaporal',
  '10K': 'Kappa',
  KAQ: 'Kaps',
  KS8: 'Karen by Simonsen',
  KT0: 'Kari Traa',
  KK1: 'Karl Kani',
  KA00: 'Karl Lagerfeld',
  K48: 'KARL LAGERFELD',
  KAS: 'Karl Lagerfeld Fragrances',
  K21: 'Kastinger',
  KM3: 'Kat Maconie',
  K05: 'kate spade new york',
  KA4: 'Kavat',
  KAV: 'Kaviar Gauche Fragrance',
  KA5: 'Kawasaki',
  K15: 'Keddo',
  KE2: 'Keds',
  KE5: 'Keen',
  KEE: 'Keepsake',
  KE9: 'Kempa',
  K09: 'KENDALL + KYLIE',
  KE3: 'Kennel + Schmenger',
  KEG: 'Kenneth Cole Fragrance',
  KED: 'Kent & Curwen',
  KW3: 'Kentucky\'s Western',
  K11: 'Kenzo',
  '1KE': 'Key Largo',
  KH4: 'KHARISMA',
  KH1: 'khujo',
  KI01: 'Kickers',
  KI1: 'Kickers',
  KIO: 'Kickers Classics',
  KIJ: 'Kids ONLY',
  KII: 'Kidzroom',
  KIN: 'Kiez',
  KIR: 'KIKO Milano',
  K13: 'Killtec',
  K0I: 'King Kerosin',
  KL2: 'King Louie',
  K04: 'Kings Of Indigo',
  KIE: 'Kings Will Dream',
  KI00: 'KIOMI',
  K44: 'KIOMI',
  KIB: 'KIOMI TALL',
  KIF: 'KIOMI Wide Fit',
  '1KI': 'Kipling',
  KJ1: 'Kjus',
  KL8: 'klairs',
  KN2: 'KnowledgeCotton Apparel',
  KOF: 'Koi Footwear',
  K00: 'Komono',
  K28: 'Konplott',
  KO4: 'Korres',
  KRI: 'Krimson Klover',
  KR1: 'Kronstadt',
  '3KU': 'KUNERT',
  KUC: 'KUNOKA',
  KU00: 'Kurt Geiger',
  KU0: 'Kurt Geiger London',
  KUB: 'KUZZOI',
  LIT: 'L\'INTERVALLE',
  LO01: 'L\'Oréal',
  LOT: 'L\'Oréal Men Expert',
  LP5: 'L\'Oréal Paris',
  L1Z: 'L\'Oréal Professionnel',
  LUH: 'L\'urv',
  LC1: 'L. CREDI',
  L300: 'L37',
  '0LF': 'L37',
  L3A: 'L37 WIDE FIT',
  L5M: 'LA DOPE',
  '2LA': 'La Martina',
  '2LP': 'La Perla',
  LAN: 'La Sportiva',
  LAQ: 'LAB',
  LAB: 'Lab Pal Zileri',
  LAX: 'Lab Series',
  LA00: 'Lace & Beads',
  LS7: 'Lace & Beads',
  LAF: 'Lace & Beads Curvy',
  LAE: 'Lace & Beads Petite',
  LAD: 'Lace & Beads Tall',
  LACO: 'Lacoste',
  LA2: 'Lacoste',
  L4S: 'Lacoste Fragrances',
  L47: 'Lacoste LIVE',
  L06: 'Lacoste Sport',
  L5D: 'Ladeheid',
  L01: 'laidbacklondon',
  LA01: 'Lamborghini',
  LAZ: 'Lamborghini',
  L27: 'Lamica',
  L4T: 'Lancaster Beauty',
  LAO: 'Larsson & Jennings',
  L83: 'LASCANA',
  L2Q: 'LAST STUDIO',
  LB3: 'Laura Biagiotti',
  LV6: 'LAURA VITA',
  L42: 'Lauren Ralph Lauren',
  LAR: 'Lauren Ralph Lauren Petite',
  L0S: 'Lauren Ralph Lauren Woman',
  L35: 'Lazamani',
  LE1: 'le coq sportif',
  LEW: 'Le Cord',
  LEQ: 'Le Fix',
  L1M: 'Le Masque Switzerland',
  L1W: 'Le Mini Macaron',
  LEL: 'Le Petit Trou',
  LS1: 'Le Specs',
  L0C: 'Le Tanneur',
  L12: 'Le Temps Des Cerises',
  L2U: 'Leabags',
  LEEE: 'Lee',
  LE4: 'Lee',
  LEZ: 'Lee Plus',
  '6LE': 'Legend',
  L11: 'Legero',
  L1P: 'Lego Bags',
  L45: 'LEGO Wear',
  LEG: 'Lemon Beret',
  LJ3: 'LEMON JELLY',
  L53: 'Leon & Harper',
  L74: 'LERROS',
  LEP: 'Les Deux',
  L4Z: 'Les Petits Basics',
  L14: 'Les Tropéziennes par M Belarbi',
  L2D: 'Leslii',
  LEN: 'Levete Room',
  LEVI: 'Levi\'s®',
  LE2: 'Levi\'s®',
  LET: 'Levi\'s® Engineered Jeans',
  LEH: 'Levi\'s® Line 8',
  L48: 'Levi\'s® Made & Crafted',
  L0M: 'Levi\'s® Plus',
  LEV: 'LEXI',
  LEO: 'Lez a Lez',
  LIW: 'LIARS & LOVERS',
  LIQ: 'Libertine-Libertine',
  L52: 'LICO',
  LI3: 'Liebeskind Berlin',
  L1F: 'Lil\'Boo',
  LIY: 'Lili Gaufrette',
  LI4: 'lilimill',
  L2T: 'Lily & Lionel',
  L2R: 'Limehaus',
  L2S: 'Limit',
  LI8: 'Limited Sports',
  L3C: 'Linda Hallberg',
  LG5: 'Lindbergh',
  L2E: 'Lindex',
  '1LN': 'LingaDore',
  L02: 'Lingerie le chat',
  LIU: 'Lipstick Queen',
  L5L: 'Little Liffner',
  LI00: 'Little Mistress',
  LM1: 'Little Mistress',
  LF6: 'Little Mistress Curvy',
  L2A: 'Little Mistress Maternity',
  LQ2: 'Little Mistress Petite',
  L2P: 'Little Mistress Tall',
  L5G: 'Little Unicorn',
  LIUJ: 'LIU JO',
  LI6: 'LIU JO',
  L25: 'Liu Jo Jeans',
  L0J: 'Live Unlimited London',
  LI2: 'Living Kitzbühel',
  LIV: 'Lixirskin',
  LK3: 'LK Bennett',
  LLOY: 'Lloyd',
  LL1: 'Lloyd',
  LB8: 'Lloyd Men\'s Belts',
  LLA: 'LLOYD SELECTED',
  L04: 'LMTD',
  LN8: 'LNDR',
  L4N: 'Local Heroes',
  LO8: 'Lodi',
  L88: 'Loeffler Randall',
  '1LJ': 'LOIS Jeans',
  LO3: 'Lola Cruz',
  LO1: 'Lola Ramona',
  L2W: 'Lonely',
  L1L: 'Longchamp',
  LOO: 'Lord & Berry',
  LO00: 'Lost Ink',
  L0U: 'Lost Ink',
  LOH: 'Lost Ink Petite',
  LOA: 'Lost Ink Plus',
  LOF: 'Lost Ink Wide Fit',
  '1LO': 'Lotto',
  LO4: 'Lottusse',
  L2B: 'LOU Lingerie',
  L46: 'Louche',
  L1R: 'Lounge Nine',
  LOW: 'Loungeable',
  LU0: 'Lousy Livin Underwear',
  L4D: 'LOVBOD',
  L3D: 'Love Brand',
  L1G: 'Love Copenhagen',
  L2N: 'Love Milk Maternity',
  LO9: 'Love Moschino',
  L2K: 'LOVE OUR PLANET by MARCO TOZZI',
  L2V: 'LOVE OUR PLANET by NOVI',
  L07: 'LOVE Stories',
  LOE: 'Love Triangle',
  LW2: 'LOVE2WAIT',
  LOB: 'Lovechild',
  LO7: 'Lowa',
  LT1: 'LTB',
  LUA: 'Luca Grossi',
  LUG: 'Lucy & Sam',
  LU9: 'Luhta',
  LUC: 'Luke 1977',
  LUF: 'Lulipa London',
  LU6: 'Lumberjack',
  LUD: 'Lumene',
  LU2: 'Lurchi',
  LUI: 'Luvia Cosmetics',
  LX0: 'Luxuar Fashion',
  LY3: 'LYDC London',
  LY2: 'Lyle & Scott',
  L62: 'Lässig',
  L3X: 'LÄST',
  LOV: 'LÖFFLER',
  LOY: 'Löwengrip',
  LA9: 'L’Autre Chose',
  MM3: 'M Missoni',
  MMB: 'M. Moustache',
  M3V: 'M2 BEAUTÉ',
  MJ5: 'Maaji',
  M3T: 'MAC',
  MT0: 'Mackintosh',
  M2Y: 'Madden by Steve Madden',
  MAJ: 'Madden Girl',
  M3J: 'Madewell',
  M14: 'Mads Nørgaard',
  M94: 'MAERZ Muenchen',
  MQ5: 'MAGIC Bodyfashion',
  M3E: 'Magicstripes',
  M10: 'Magnanni',
  M4X: 'MAHONY',
  M96: 'Maidenform',
  MAR: 'Mainio',
  M4U: 'Maison Courch',
  M5B: 'Maison Hēroïne',
  M6E: 'MAITRE',
  MAL: 'maje',
  M6O: 'Make up Revolution',
  M4A: 'Makeup Eraser',
  MK9: 'Makia',
  MA06: 'Mamalicious',
  M64: 'MAMALICIOUS',
  M7V: 'Mamalicious Curve',
  M73: 'Mammut',
  M4C: 'Man Cave',
  MANG: 'Mango',
  M91: 'Mango',
  M5H: 'Manhattan Cosmetics',
  M5D: 'MANÉ',
  M4J: 'Mara Mea',
  M4R: 'Marc Cain',
  MAJA: 'Marc Jacobs',
  MJ4: 'Marc Jacobs',
  MARC: 'Marc O\'Polo',
  MA3: 'Marc O\'Polo',
  OP5: 'Marc O\'Polo DENIM',
  M3X: 'Marc O\'Polo PURE',
  MAW: 'Marcel Ostertag x Tamaris',
  MA03: 'Marco Tozzi',
  M31: 'Marco Tozzi',
  M6A: 'Marco Tozzi by Guido Maria Kretschmer',
  M6F: 'MARCUS',
  M75: 'Marella',
  M4V: 'Margaret Dabbs London',
  MAY: 'Maria Black',
  MAP: 'Mariamare',
  M5M: 'Marikoo',
  M4K: 'Marimekko',
  M28: 'Maripé',
  MJ7: 'Marjo',
  QM4: 'Marks & Spencer London',
  MAM: 'Marni',
  M77: 'Marshall',
  MR6: 'Marshall Artist',
  M5N: 'Martin Asbjørn',
  M4M: 'Maryan Mehlhorn',
  M3U: 'Maréna Beauté',
  M3W: 'Masai',
  M09: 'Mascara',
  M8J: 'Maskulin',
  M38: 'Mason\'s',
  M3I: 'Massimo Dutti',
  M3C: 'Master & Dynamic',
  M60: 'Matinique',
  M5U: 'Matrix',
  M03: 'Matt & Nat',
  MA6: 'Mavi',
  MF1: 'Max Factor',
  M1W: 'Max Mara Hosiery',
  M1X: 'Max Mara Leisure',
  MQ9: 'MAX&Co.',
  AX7: 'Maximo',
  MA01: 'Maya Deluxe',
  M2Z: 'Maya Deluxe',
  M5E: 'Maya Deluxe Maternity',
  MJ3: 'Maybelline New York',
  M29: 'Maze',
  MT3: 'Maître',
  MB1: 'mbyM',
  MC1: 'MCM',
  MQ1: 'McQ Alexander McQueen',
  MEQ: 'Melania',
  MEX: 'Melawear',
  ME9: 'Melissa',
  M47: 'Mellow Yellow',
  M6V: 'Melody Lashes',
  ME2: 'Melvin & Hamilton',
  MEP: 'Men\'s Society',
  ME3: 'Menbur',
  OR2: 'Menil',
  MEF: 'Mennace',
  '3ME': 'Merc',
  MEN: 'Mercer Amsterdam',
  MEJ: 'Merchcode',
  MEM: 'Merci Handy',
  ME1: 'Merrell',
  MEV: 'Metissier',
  ME4: 'Mexx',
  MES: 'Mexx Fragrance',
  MII: 'Miansai',
  MICH: 'Michael Kors',
  '1MI': 'Michael Kors',
  MIA: 'Michael Kors Access',
  MK1: 'MICHAEL Michael Kors',
  M83: 'MIISTA',
  MIH: 'mikk-line',
  M7J: 'Milk it',
  M50: 'Millet',
  M12: 'Milly',
  M8G: 'MIM Shoes',
  MIY: 'Mimitika',
  T0X: 'mine to five TOM TAILOR',
  MIF: 'Minelli',
  MI6: 'MINI A TURE',
  MM7: 'Mini Molly',
  MR1: 'Mini Rodini',
  MI4: 'Minimum',
  M86: 'MINKPINK',
  MI1: 'Minnetonka',
  MI02: 'mint&berry',
  M32: 'mint&berry',
  M4Q: 'mint&berry wide fit',
  M07: 'Minus',
  MN6: 'Minymo',
  M4T: 'Mio',
  M7K: 'MIREIA PLAYÀ',
  MIV: 'Mis Pepas',
  M6T: 'MISBHV',
  MIX: 'Miss Green',
  MI00: 'Miss Selfridge',
  MF9: 'Miss Selfridge',
  PY0: 'Miss Selfridge Petite',
  M4S: 'Miss Selfridge Wide Fit',
  MI3: 'Miss Sixty',
  MI01: 'Missguided',
  M0Q: 'Missguided',
  M6M: 'Missguided Fragrances',
  M5Q: 'Missguided Maternity',
  M0V: 'Missguided Petite',
  M0U: 'Missguided Plus',
  MIG: 'Missguided Tall',
  MIT: 'Missha',
  MISS: 'Missoni',
  '6MI': 'Missoni',
  M4O: 'Missoni Kids',
  M0M: 'Mister Tee',
  MN8: 'Mitchell & Ness',
  MIS: 'Mizon',
  M27: 'Mizuno',
  MJ1: 'MJUS',
  MMA: 'MM6 Maison Margiela',
  '21M': 'Mo',
  Y05: 'MOA - Master of Arts',
  M2A: 'Modern Eternity',
  MO4: 'Modström',
  M90: 'Moleskine',
  M61: 'Molly Bracken',
  M85: 'Molo',
  M51: 'Molten',
  MOQ: 'Monki',
  MOE: 'Mons Royale',
  MOH: 'Mont Blanc',
  MOO: 'Monta Juniors',
  M45: 'Moon Boot',
  M58: 'More & More',
  M59: 'Morgan',
  MOG: 'MOROTAI',
  MX9: 'Mos Mosh',
  MOSC: 'MOSCHINO',
  '6MO': 'MOSCHINO',
  M05: 'MOSCHINO SWIM',
  MW8: 'Moschino Underwear',
  M0Y: 'Moss Copenhagen',
  MOL: 'Mossman',
  MH3: 'Mother',
  MP4: 'Mother of Pearl',
  MOC: 'mothercare',
  MOD: 'Moves',
  MPA: 'MP Denmark',
  MRB: 'Mr Bear Family',
  MRC: 'Mr Natty',
  GG7: 'Mr. GUGU & Miss GO',
  MRA: 'MRZ',
  MG6: 'MSGM',
  MT7: 'mtng',
  M0G: 'MUCHACHOMALO',
  MUF: 'Mulberry',
  MUE: 'Musse & Cloud',
  MU3: 'Mustang',
  MVA: 'MVMT',
  MYC: 'My Magic Mud',
  TOL: 'MY TRUE ME TOM TAILOR',
  MYE: 'My White Secret',
  MYD: 'Mykke Hofmann',
  MY00: 'myMo',
  '1MY': 'myMo',
  MYJ: 'myMo at night',
  MYK: 'myMo ATHLSR',
  MYL: 'myMo KIDS',
  MYI: 'myMo ROCKS',
  M7X: 'Mäser',
  M2G: 'Müsli by GREEN COTTON',
  NA02: 'NA-KD',
  NAA: 'NA-KD',
  NAQ: 'NA-KD Tall',
  NAR: 'NAE Vegan Shoes',
  NA5: 'NAF NAF',
  NAT: 'Nagev',
  NAF: 'Nails Inc',
  NA8: 'Name it',
  '1NA': 'Nanga',
  NA00: 'Napapijri',
  NA6: 'Napapijri',
  NAH: 'Napapijri The Tribe',
  NA1: 'Native',
  NY2: 'Native Youth',
  NAX: 'Natural Vibes',
  NW1: 'Natural World',
  NAW: 'NATURECAN',
  NA3: 'Naturino',
  NAP: 'Navahoo',
  NT5: 'Needle & Thread',
  NEF: 'Neighbourhood Botanicals',
  NE01: 'Neil Barrett',
  '4NE': 'Neil Barrett',
  BLI: 'Neil Barrett BLACKBARRETT',
  N21: 'Neom',
  NE1: 'Neosens',
  NET: 'NeroGiardini',
  NEJ: 'Nerve',
  ND8: 'Neuw',
  NE03: 'Never Fully Dressed',
  NEN: 'Never Fully Dressed',
  NEZ: 'Never Fully Dressed Petite',
  N0L: 'Never Fully Dressed Tall',
  NE2: 'New Balance',
  NE3: 'New Era',
  NEM: 'NEW girl ORDER',
  NEP: 'New Layer',
  NE00: 'New Look',
  NL0: 'New Look',
  NL6: 'New Look 915 Generation',
  N32: 'New Look Curves',
  N0B: 'New Look Maternity',
  NL7: 'New Look Petite',
  NEB: 'New Look Tall',
  NED: 'New Look Wide Fit',
  '1NE': 'Newline',
  NER: 'Newport Bay Sailing Club',
  NX3: 'Next',
  NG0: 'NGHTBRD',
  NIK: 'Nialaya',
  N05: 'Nicce',
  NIY: 'Nicki Studios',
  NIJ: 'Night Addict',
  NIS: 'Nikben',
  NIKE: 'Nike',
  NI4: 'Nike Golf',
  N12: 'Nike Performance',
  NS4: 'Nike SB',
  NI1: 'Nike Sportswear',
  NIR: 'Nike Underwear',
  NIO: 'NIKKIE',
  NIH: 'Nioxin',
  NIF: 'Nip+Fab',
  NI01: 'Nivea',
  NIP: 'Nivea',
  NIQ: 'Nivea Men',
  NK3: 'NKD/BTY',
  NEG: 'Nly by Nelly',
  NN9: 'NN07',
  NO8: 'No Name',
  NN1: 'Noa Noa',
  NOV: 'NOANI',
  N02: 'Noclaim',
  N0N: 'NOELANI',
  NON: 'NOIRE LINE',
  NO00: 'Noisy May',
  NM3: 'Noisy May',
  NOY: 'Noisy May Curve',
  NM5: 'Noisy May Petite',
  NOB: 'Noisy May Tall',
  NOU: 'Nominal',
  NOI: 'NON COMMUN',
  NM0: 'Noose & Monkey',
  N14: 'Noppies',
  N0G: 'Noppies Studio',
  N0R: 'Nora Rose',
  NOP: 'Nordgreen',
  NOE: 'NORR',
  NOO: 'Norrøna',
  NO6: 'North Sails',
  NOF: 'Northskull',
  N0D: 'Noé & Zoë',
  NUF: 'NU-IN',
  NB2: 'Nubikk',
  NU2: 'Nudie Jeans',
  NUH: 'NUMERO 00',
  NUB: 'Nuvega Lash',
  NY6: 'Nyx Professional Makeup',
  NY7: 'Nyze',
  N31: 'N°21',
  NUC: 'Núnoo',
  NU1: 'Nümph',
  ON5: 'O\'Neill',
  OA3: 'Oakley',
  OA1: 'Oakwood',
  OB0: 'Obey Clothing',
  OB00: 'Object',
  OB1: 'Object',
  OB8: 'Object Petite',
  OB7: 'Object Tall',
  OD2: 'Odacité',
  OD3: 'Odeme',
  OD1: 'ODLO',
  OF00: 'Office',
  OF2: 'Office',
  OF4: 'Office Wide Fit',
  OF7: 'OFRA',
  OF8: 'oftt',
  OH0: 'ohma!',
  OI1: 'Oilily',
  OLA: 'Oliveda',
  OLC: 'Oliver Bonas',
  OB6: 'Olivia Burton',
  OLG: 'Olivia Rubin',
  OLYM: 'Olymp',
  OL4: 'OLYMP',
  OL8: 'OLYMP Level Five',
  OL7: 'OLYMP Luxor',
  OL0: 'OLYMP No. Six',
  ON4: 'One Green Elephant',
  ON9: 'one more story',
  TE7: 'One Teaspoon',
  ONJ: 'Ones Supply Co.',
  TI3: 'Onitsuka Tiger',
  ON00: 'ONLY',
  ON3: 'ONLY',
  OS3: 'Only & Sons',
  ONA: 'ONLY Carmakoma',
  OP4: 'ONLY Petite',
  NL2: 'ONLY Play',
  ONE: 'ONLY PLAY Petite',
  ONF: 'ONLY PLAY Tall',
  OS4: 'ONLY SHOES',
  OND: 'ONLY Tall',
  ON2: 'Onzie',
  OO0: 'OOSC',
  CE7: 'Opening Ceremony',
  OP6: 'OPI',
  OP2: 'OppoSuits',
  PC7: 'Opus',
  RL6: 'Orelia',
  P52: 'Original Penguin',
  OK0: 'OshKosh',
  '2KE': 'Otto Kessler',
  OU7: 'Ouai',
  OU0: 'Outerknown',
  OU8: 'Outerstuff',
  OV3: 'overlay official',
  OV0: 'OVS',
  OW0: 'OW Intimates',
  OX2: 'Oxitaly',
  OY00: 'Oysho',
  OY1: 'OYSHO',
  OY2: 'OYSHO_SPORT',
  P0X: 'P.E Nation',
  P4A: 'P448',
  P0Z: 'Pacific and Co',
  PA2: 'Paco Gil',
  PD1: 'Paddock\'s',
  PAH: 'Pai skincare',
  P23: 'Paige',
  P12: 'Pajar',
  P13: 'Palladium',
  PM0: 'Palmers',
  PB1: 'Paloma Barceló',
  PA3: 'Panama Jack',
  PA4: 'Pantofola d\'Oro',
  PAO: 'paolifirenze',
  PA6: 'Papillio',
  PAX: 'Paprika',
  P0Y: 'Papu',
  PA01: 'Paradox London',
  P0M: 'Paradox London Pink',
  PAP: 'Paradox London Wide Fit',
  P1F: 'PARELLEX',
  P0G: 'PARFOIS',
  P0H: 'Parkland',
  P21: 'Part Two',
  P20: 'Passionata',
  PA9: 'Patagonia',
  P10: 'Pataugas',
  P14: 'Patrizia Pepe',
  PAK: 'Paul & Joe Beaute',
  PAQ: 'Paul Green',
  PASM: 'Paul Smith',
  PS9: 'Paul Smith',
  PAJ: 'Paul Smith Junior',
  PAS: 'Paula Janz Maternity',
  PC6: 'Paulina',
  PV1: 'Pavement',
  PA1: 'Pax',
  PBA: 'PB 0110',
  PDA: 'PDPAOLA',
  PE01: 'Peak Performance',
  PE4: 'Peak Performance',
  PEO: 'Peak Performance Urban',
  PE7: 'Pedag',
  PEQ: 'Pedro del Hierro',
  PM7: 'Pedro Miralles',
  PEP: 'Pegador',
  PE8: 'Penfield',
  '4PE': 'Penn',
  PEN: 'PEP',
  PE1: 'Pepe Jeans',
  PE9: 'Pepino',
  PEV: 'PEPPERCORN',
  PEJ: 'Percy & Reed',
  PEM: 'Percy Nobleman',
  P63: 'PERLATO',
  PET: 'Perry Ellis America',
  P03: 'Persol',
  PQ0: 'Persona by Marina Rinaldi',
  PEK: 'Pestle & Mortar',
  PE02: 'Peter Kaiser',
  PE2: 'Peter Kaiser',
  PEG: 'Peter Kaiser Wide Fit',
  PT3: 'Peter Thomas Roth',
  P68: 'Petrol Industries',
  PB7: 'Peuterey',
  PH0: 'Phenix',
  PIM: 'Piazza Italia',
  PI3: 'Picard',
  PIL: 'pick & PACK',
  LIPI: 'Pieces',
  PE3: 'Pieces',
  PIU: 'Pieces Curve',
  PIV: 'Pieces Maternity',
  PIT: 'Pieces Petite',
  PIP: 'PIECES Tall',
  PI00: 'Pier One',
  PI9: 'Pier One',
  PIG: 'Pier One Wide Fit',
  PIH: 'Pieszak',
  P0K: 'Pietro Brunelli',
  PI5: 'Pikolinos',
  PI8: 'Pilgrim',
  P0F: 'Pimkie',
  PIS: 'Pink Soda',
  PI01: 'Pinko',
  P69: 'Pinko',
  PIJ: 'Pinko Up',
  P67: 'Pinocchio',
  PD7: 'Pinto Di Blu',
  '1PQ': 'Piquadro',
  PIY: 'Pius Gabor',
  PJ3: 'PJ Salvage',
  PLG: 'Playful Promises',
  PL3: 'Playshoes',
  P0E: 'PLUS EIGHTEEN',
  PX8: 'POC',
  '6PO': 'Polaroid',
  P73: 'Police',
  RALP: 'Polo Ralph Lauren',
  PO2: 'Polo Ralph Lauren',
  P62: 'Polo Ralph Lauren Big & Tall',
  PO7: 'Polo Ralph Lauren Golf',
  RP5: 'Polo Sport Ralph Lauren',
  PF8: 'POLOLO',
  PK4: 'Pomkin',
  PQ1: 'Pons Quintana',
  P2E: 'Pontiki',
  POM: 'Popband',
  PD0: 'Porsche Design',
  POJ: 'Pour Moi',
  P24: 'Prada',
  PRB: 'Prada Linea Rossa',
  PRT: 'PRAY',
  PRV: 'Pre End',
  PRW: 'Presly&Sun',
  PRU: 'PRET POUR PARTIR',
  PR1: 'Pretty Ballerinas',
  '5PP': 'Pretty Polly',
  PRH: 'PRIMA MODA',
  PR3: 'Primigi',
  PRO: 'Primitive',
  PRG: 'Primosole',
  P16: 'Princesse tam.tam',
  PR6: 'Prinzessin Lillifee',
  PY5: 'Produkt',
  PR01: 'Proenza Schouler',
  PQ4: 'Proenza Schouler',
  P1Y: 'Proenza Schouler White Label',
  PRR: 'Progetto Quid',
  PRP: 'Projekts NYC',
  PRY: 'Pronovias',
  P51: 'property of',
  PRJ: 'Proraso',
  PS7: 'PS Paul Smith',
  PUA: 'Public Desire',
  PUC: 'PULL&BEAR',
  PUH: 'PULZ',
  PUMA: 'Puma',
  PU1: 'Puma',
  PU5: 'Puma Golf',
  '1PB': 'Punto Blanco',
  PU2: 'Pura Lopez',
  PUG: 'pure cashmere',
  PUD: 'pure pure by BAUER',
  PY8: 'PYRENEX',
  PY1: 'PYUA',
  QS1: 'Q/S designed by',
  Q01: 'QUAY AUSTRALIA',
  QUC: 'Queen Kerosin',
  QM1: 'Queen Mum',
  QU1: 'Quiksilver',
  RW2: 'R. M. WILLIAMS',
  RAK: 'Raaw by Trice',
  RZ1: 'Rachel Zoe',
  RAF: 'Radà',
  CHA: 'Raeburn',
  R07: 'rag & bone',
  RAN: 'Ragged Jeans',
  RA01: 'Ragwear',
  R59: 'Ragwear',
  RAC: 'Ragwear Plus',
  RA00: 'Raid',
  RAD: 'RAID',
  RAI: 'RAID Wide Fit',
  RI0: 'Rains',
  RAV: 'Ralph Lauren Fragrance',
  R05: 'RALPH Ralph Lauren',
  RA9: 'Rapisardi',
  RA6: 'Rare London',
  RA5: 'RAS',
  RAU: 'RATED GREEN',
  RAM: 'Raw Naturals',
  RA2: 'Ray-Ban',
  RG5: 'Re-Gen',
  REM: 'Re.draft',
  R0O: 'Re:Covered',
  REI: 'RE:DESIGNED',
  RED: 'Real Techniques',
  RM6: 'Rebecca Minkoff',
  REH: 'Recipe For Men',
  REY: 'recolution',
  R24: 'Red V',
  R06: 'Redefined Rebel',
  R1N: 'Redi Fashion',
  REZ: 'Redken',
  R27: 'Redskins',
  REEB: 'Reebok',
  RE5: 'Reebok',
  RE0: 'Reebok Classic',
  RE2: 'Reef',
  RF7: 'Refresh',
  R23: 'Regatta',
  RM7: 'Reima',
  R19: 'Religion',
  R15: 'Remonte',
  R0L: 'Rens Original',
  R00: 'Repeat',
  REP: 'Repetto',
  RE00: 'Replay',
  RE3: 'Replay',
  REN: 'Replay Plus',
  REO: 'Replay Sportlab',
  R62: 'Resteröds',
  REW: 'RETHINK Status',
  RJ2: 'Retour Jeans',
  R0C: 'RETROSUPERFUTURE',
  R31: 'Reusch',
  REE: 'Revitalash',
  REK: 'Revival Tee',
  '1RE': 'Revlon',
  RE02: 'Revolution',
  RE6: 'REVOLUTION',
  R0H: 'Revolution Skincare',
  '2RH': 'Rhythm',
  RIJ: 'RIANI',
  RI5: 'Rich & Royal',
  RI3: 'Richter',
  RI2: 'Ricosta',
  RI1: 'Rieker',
  R96: 'Rika',
  RI7: 'Rip Curl',
  RIH: 'Ripe',
  RIB: 'RISA',
  RI00: 'River Island',
  RI9: 'River Island',
  RIL: 'River Island Maternity',
  RIF: 'River Island Petite',
  RIE: 'River Island Plus',
  RIN: 'River Island Tall',
  RID: 'River Island Wide Fit',
  RV1: 'RIVIERAS',
  RO1: 'Robeez',
  CAVA: 'Roberto Cavalli',
  '1RO': 'Roberto Cavalli',
  R66: 'Roberto Collina',
  RO3: 'Rocket Dog',
  R13: 'Roeckl',
  RO9: 'Rohde',
  ROE: 'Rojo',
  R98: 'Roksanda',
  ROF: 'Rolla\'s',
  R11: 'Romika',
  ROD: 'Ron Dorff',
  ROA: 'Roosevelt',
  ROP: 'Rooskickx',
  R43: 'Rosantica',
  RM0: 'Rosemunde',
  ROL: 'Rosental Organics',
  ROJ: 'Rossignol',
  RO5: 'Roxy',
  R0A: 'Royal - Ego',
  ROW: 'Royal Denim Division by Jack & Jones',
  RO4: 'Royal RepubliQ',
  ROV: 'Royce Lingerie',
  RUE: 'Rubi Shoes by Cotton On',
  RUH: 'Rubi Shoes by Cotton On Wide Fit',
  RUA: 'Rukka',
  RUF: 'Russell Athletic Eagle R',
  RV4: 'RVCA',
  REG: 'Résumé',
  SWC: 'S\'well',
  SOLI: 's.Oliver',
  SO2: 's.Oliver',
  SOA: 's.Oliver BLACK LABEL',
  SG8: 'Sail Racing',
  S28: 'Saint Tropez',
  S48: 'Salamander',
  S20: 'Salewa',
  SAL: 'Sally Hansen',
  SA5: 'Salomon',
  SAV: 'Salt & Stone',
  '3SF': 'Salvatore Ferragamo',
  S49: 'Sam Edelman',
  SA3: 'Samsøe Samsøe',
  SAB: 'San Marina',
  SAA: 'Sand Copenhagen',
  SAN: 'Sand&Sky',
  SV0: 'Sandqvist',
  SAD: 'sandro',
  SANE: 'Sanetta',
  SA1: 'Sanetta',
  S0C: 'Sanetta fiftyseven',
  SA4: 'Sanita',
  '5SA': 'Sans Complexe',
  SAZ: 'Sansibar Shoes',
  '7SA': 'Santa Cruz',
  SAO: 'Sante',
  S23: 'Saucony',
  SAM: 'SAVAGE X FENTY',
  TD0: 'Save the duck',
  SCF: 'Scalpers',
  P97: 'Scapa',
  QS3: 'Scarpa',
  S59: 'Schiesser',
  SC1: 'Schmoove',
  WD2: 'Schmuddelwedda',
  SC2: 'Scholl',
  SC01: 'Schott',
  S37: 'Schott',
  SD0: 'Schott Made in USA',
  SC7: 'Schöffel',
  SCOT: 'Scotch & Soda',
  SC3: 'Scotch & Soda',
  SCN: 'Scotch & Soda Fragrance',
  SC9: 'Scotch R\'Belle',
  SC6: 'Scotch Shrunk',
  SCP: 'scott barnes',
  KEC: 'Sea Ranch',
  S19: 'Seafolly',
  SEZ: 'Seasalt Cornwall',
  SEP: 'SEB MAN',
  SE2: 'Sebago',
  S2Y: 'Sebastian Professional',
  SEO: 'Seche Vite',
  SE4: 'Second Female',
  SE3: 'See by Chloé',
  SET: 'Seidenfelt',
  '3SE': 'Seidensticker',
  SEU: 'Sekonda',
  SEV: 'Seksy',
  SEK: 'Selahatin',
  SE01: 'Selected',
  SE5: 'Selected Femme',
  SEW: 'Selected Femme Curve',
  SEL: 'Selected Femme Petite',
  SEM: 'Selected Femme Tall',
  SE6: 'Selected Homme',
  S0T: 'Sense Organics',
  S1S: 'Seraphine',
  K29: 'Serge Pariente',
  S16: 'sergio tacchini',
  SH4: 'Shabbies Amsterdam',
  SH9: 'SHAN RAHIMKHAN',
  SHM: 'Shashi',
  SHJ: 'Shaveworks',
  SHF: 'Shelby & Sons',
  S30: 'Shepherd',
  OR3: 'Shine Original',
  S66: 'Shiwi',
  OC5: 'Shock Absorber',
  SB6: 'Shoe The Bear',
  SHG: 'shoeb76',
  E39: 'Shoesme',
  P02: 'Shoo Pom',
  H49: 'Short Stories',
  THS: 'SHRINE',
  S0G: 'Sif Jakobs Jewellery',
  SIF: 'SIKSILK',
  '2SI': 'Silvio Tossi',
  SR7: 'Simone Pérèle',
  SI00: 'Simply Be',
  SIE: 'Simply Be',
  SIO: 'SINNERS ATTIRE',
  SIM: 'Siren',
  '7SI': 'Sisley',
  SI01: 'SISTA GLAM',
  SID: 'Sista Glam',
  SIL: 'SISTA GLAM PETITE',
  QS0: 'Sister Jane',
  SQ5: 'Six Ames',
  SIB: 'Sixth June',
  IX0: 'Sixtyseven',
  SK00: 'Skagen',
  '2SK': 'Skagen',
  SKA: 'Skagen Connected',
  SKE: 'Skandinavisk',
  SKEC: 'Skechers',
  SK1: 'Skechers',
  P07: 'Skechers Performance',
  SK2: 'Skechers Sport',
  SKD: 'Skechers Wide Fit',
  SKJ: 'Skin Gym',
  SKB: 'Skinnydip',
  SS8: 'Skins',
  SK7: 'Skiny',
  SKF: 'Skip Hop',
  SLA: 'Slacks & Co.',
  SLF: 'Sleek',
  SL2: 'Sloggi',
  YS2: 'Slydes',
  WO9: 'Smartwool',
  SMD: 'Smilodox',
  '1SM': 'Smith Optics',
  SMC: 'Smitten Organic',
  SMA: 'Småfolk',
  SS9: 'Sneaky Steve',
  '1SN': 'SNÖ of Sweden',
  SO9: 'Soaked in Luxury',
  SOK: 'Society',
  SOR: 'Soeur',
  SG9: 'Soft Gallery',
  R67: 'Soft Rebels',
  SO1: 'Softclox',
  SO3: 'Softinos',
  SOO: 'Soko',
  SO4: 'Solid',
  QS6: 'Solid & Striped',
  S2S: 'Solidu',
  Y03: 'someday.',
  SY9: 'Sonia Rykiel',
  SO6: 'Sorel',
  SOX: 'Soroci',
  SU0: 'Soulland',
  S1X: 'SOULSTAR',
  SOH: 'South Beach',
  '2SO': 'Southpole',
  SO8: 'Soyaconcept',
  SP5: 'Spalding',
  SX1: 'Spanx',
  SPG: 'Spectrum',
  '1SP': 'Speedo',
  SP1: 'Sperry',
  SZ4: 'Spikes & Sparrow',
  BH7: 'Spiral Bags',
  SP3: 'Spoom',
  SM9: 'Sportmax',
  XC0: 'Sportmax Code',
  SPF: 'Sprekenhus',
  SPA: 'Spring Maternity',
  FI0: 'Springfield',
  SY0: 'Spyder',
  SQ0: 'St. Tropez',
  STF: 'Staccato',
  T57: 'Stance',
  S2P: 'STAPLE PIGEON',
  S2O: 'StarFlips',
  S2E: 'STARSKIN',
  X11: 'Starter',
  STP: 'State of Elevenate',
  S2I: 'Steambase',
  STC: 'Steffen Schraut',
  ST02: 'Steiff',
  S15: 'Steiff Collection',
  STZ: 'Steiff Shoes',
  ST03: 'Stella McCartney',
  S0Y: 'Stella McCartney',
  SM6: 'Stella McCartney Lingerie',
  SV5: 'Stella Nova',
  S2G: 'STEREOTYPE',
  ST01: 'Steve Madden',
  ST3: 'Steve Madden',
  SP6: 'Steven New York',
  S2F: 'Stevie May',
  S2L: 'Stieglitz',
  STJ: 'Still Nordic',
  STN: 'STOP THE WATER WHILE USING ME!',
  STH: 'Stradivarius',
  S43: 'Strellson',
  S08: 'Strenesse',
  S2H: 'Stripe + Stare',
  STY: 'StriVectin',
  ST5: 'Stuart Weitzman',
  STX: 'STUDIO ID',
  S3X: 'STUFF MAKER',
  S05: 'Stutterheim',
  SUU: 'SUBU',
  SUP: 'Sugarhill Brighton',
  SU3: 'Suit',
  SUV: 'Suitmeister',
  SUJ: 'Sunheroes',
  SUF: 'Sunnylife',
  SN5: 'Sunseeker',
  SUN: 'Sunuva',
  SU2: 'Superdry',
  LE3: 'Superfit',
  SU1: 'Superga',
  S86: 'Supermom',
  SUM: 'Supermood',
  SUS: 'SuperRebel',
  SUO: 'Supply & Demand',
  SUE: 'SURI FREY',
  '4SW': 'Swarovski',
  SWB: 'Swatch',
  SWE: 'Sweaty Betty',
  SWD: 'Swedish Stockings',
  SWG: 'SWEED Lashes',
  '2SW': 'sweet deluxe',
  SW8: 'Sweet SKTBS',
  SW00: 'Swing',
  SG7: 'Swing',
  S0O: 'Swing Curve',
  SWH: 'Swiss Clinic',
  SW2: 'Swiss Military Hanowa',
  S2U: 'Søn of Barberians',
  TAQ: 'taddy',
  TA0: 'Taifun',
  T59: 'Tailored Originals',
  TAB: 'Talence',
  TA00: 'Tamaris',
  TA1: 'Tamaris',
  FAF: 'Tamaris Fashletics',
  TAD: 'Tamaris Heart & Sole',
  TAI: 'Tamaris Pure Relax',
  TAG: 'Tangle Teezer',
  TC1: 'Tartine et Chocolat',
  TT9: 'Tata Italia',
  TAC: 'Tateossian',
  TE4: 'Ted Baker',
  TS1: 'Teddy Smith',
  TL4: 'Temperley London',
  TP5: 'Ten Points',
  TE2: 'Teva',
  TF00: 'TFNC',
  TF1: 'TFNC',
  TFB: 'TFNC Curve',
  TFC: 'TFNC Maternity',
  TF9: 'TFNC Petite',
  TFA: 'TFNC Tall',
  T0S: 'TH&TH',
  THQ: 'the Balm',
  T1P: 'The Bonnie Mob',
  C5A: 'The Couture Club',
  T0W: 'The East Order',
  T1H: 'The GoodPeople',
  THA: 'The Kooples',
  THT: 'The Library of Fragrance',
  LM5: 'The Marc Jacobs',
  T1Z: 'The Neighbourgoods',
  THN: 'The New',
  TH3: 'The North Face',
  T0U: 'The Perfect V',
  THX: 'The Piu',
  THJ: 'The Ragged Priest',
  SIJ: 'THE SIGN TRIBE',
  T2F: 'The Striped Cat',
  T40: 'Theory',
  TH1: 'Think!',
  T1A: 'Third Form',
  T0P: 'Thomas Clipper',
  T0Z: 'Thought',
  THC: 'Threadbare',
  T0B: 'Three Floor',
  T0R: 'Thurley',
  TF3: 'Tiffosi',
  TID: 'Tiger Mist',
  TIGE: 'Tiger of Sweden',
  TI5: 'Tiger of Sweden',
  TN2: 'Tiger of Sweden Jeans',
  TG0: 'Tigha',
  TIB: 'Tigi',
  TI1: 'Timberland',
  TX1: 'Timex',
  TIC: 'TINYCOTTONS',
  TJ0: 'TJ Collection',
  TOP: 'Tobias & The Bear',
  '2TO': 'Tom Ford',
  T1K: 'Tom Hemp\'s',
  '4JO': 'Tom Joule',
  TOMT: 'Tom Tailor',
  TO2: 'TOM TAILOR',
  TO7: 'TOM TAILOR DENIM',
  TOO: 'TOM TAILOR MEN PLUS',
  TOMM: 'Tommy Hilfiger',
  TO1: 'Tommy Hilfiger',
  TOY: 'Tommy Hilfiger Curve',
  TOQ: 'Tommy Hilfiger Fragrance',
  T10: 'Tommy Hilfiger Tailored',
  TOB: 'Tommy Jeans',
  T2C: 'Tommy Jeans Curve',
  T1O: 'Tommy Jeans Plus',
  TOI: 'Tomorrow',
  TO3: 'TOMS',
  TO8: 'TomShot',
  TOF: 'Toni & Guy',
  TN4: 'Toni Sailer',
  TOS: 'Tonsure',
  T1L: 'TOP GUN',
  TP8: 'Topman',
  TO00: 'Topshop',
  TP7: 'Topshop',
  TOU: 'Topshop Beauty',
  T0I: 'Topshop Maternity',
  TQ0: 'Topshop Petite',
  TOA: 'Topshop Tall',
  TOG: 'Topshop Wide Fit',
  TO02: 'Toral',
  TOE: 'Toral',
  TOM: 'Toral Wide Fit',
  T07: 'Tory Burch',
  TO9: 'Tosca Blu',
  TRU: 'Trendyol',
  TT1: 'triaction by Triumph',
  TRZ: 'Trina Turk',
  TRY: 'Trine\'s Wardrobe',
  T37: 'Triple2',
  TRIU: 'Triumph',
  TR5: 'Triumph',
  TRI: 'TrollKids',
  TR1: 'True Religion',
  TR03: 'True Violet',
  TRD: 'True Violet',
  TRT: 'True Violet Maternity',
  TRV: 'True Violet Petite',
  TRW: 'True Violet Tall',
  TRB: 'TruSox',
  TR00: 'Trussardi',
  T04: 'Trussardi',
  T08: 'Trussardi Jeans',
  TU9: 'TUFFSKULL',
  TU4: 'Tumble \'n dry',
  TUA: 'Turtledove',
  TUB: 'Tutti Rouge',
  TW7: 'Tweezerman',
  TWD: 'Twin & Chic',
  TW3: 'TWINSET',
  TW00: 'Twintip',
  TW4: 'TWINTIP',
  TWB: 'Twintip Plus',
  TW1: 'Twist & Tango',
  TWC: 'Twisted Tailor',
  TY1: 'TYPO',
  UC4: 'U Collection by Forever Unique',
  US2: 'U.S. Polo Assn.',
  UG1: 'UGG',
  UH1: 'Uhlsport',
  UL5: 'Ultrasun',
  UM0: 'UMA PARKER',
  UM00: 'Umbro',
  UM1: 'Umbro',
  UM4: 'Umbro Projects',
  UNG: 'Unauthorized',
  UNL: 'Uncommon Souls',
  UN2: 'Under Armour',
  UNH: 'Underprotection',
  UNC: 'Undress Code',
  UNK: 'UNIQUE 21',
  UN00: 'Unisa',
  UN1: 'Unisa',
  SPH: 'Unisa Wide Fit',
  UNB: 'UNOde50',
  UO3: 'UOMA',
  UP4: 'Uppercut',
  URI: 'URANG',
  URJ: 'URBAN ALCHEMY',
  URE: 'Urban Apothecary',
  UR00: 'Urban Classics',
  UR6: 'Urban Classics',
  URA: 'Urban Classics Curvy',
  URF: 'Urban Threads',
  UR3: 'Urbanears',
  UR7: 'Urbanista',
  URB: 'URBN SAINT',
  '1US': 'usha',
  US1: 'Uslu Airlines',
  UT4: 'Uterqüe',
  UZ0: 'Uzurii',
  VA1: 'Vagabond',
  VA01: 'Valentino',
  '5VA': 'Valentino Bags',
  VAP: 'Valet Studio',
  VL4: 'van Laack',
  VL7: 'Van Lier',
  '0VB': 'Vanessa Bruno',
  VAL: 'Vanity Fair Lingerie',
  VA2: 'Vans',
  VA6: 'Vanzetti',
  VR0: 'Varley',
  VA4: 'Vaude',
  VJ2: 'Veja',
  '2VE': 'Venice Beach',
  VEM: 'Vera Wang Fragrances',
  VER: 'VERBENAS',
  VERO: 'Vero Moda',
  VE1: 'Vero Moda',
  VEE: 'Vero Moda Curve',
  VM0: 'Vero Moda Petite',
  VEB: 'Vero Moda Tall',
  VEJ: 'Vero Moda Wide Fit',
  VERS: 'Versace',
  '1VE': 'Versace',
  VC1: 'Versace Collection',
  VEI: 'Versace Jeans Couture',
  VEF: 'Versace Watches',
  VED: 'VERSO skincare',
  VE0: 'Versus Versace',
  VIC: 'Vibe Harsløf',
  VB0: 'Vibram Fivefingers',
  V09: 'Victoria Beckham',
  VI2: 'Victoria Shoes',
  VIT: 'Victoria Victoria Beckham',
  VD2: 'Vidorreta',
  VIA: 'Viggo',
  VI1: 'Viking',
  VID: 'Viktor&Rolf',
  VI02: 'VILA',
  V10: 'Vila',
  VIP: 'VILA PETITE',
  V0A: 'VILA TALL',
  VIK: 'Villa d\'Assia',
  VI00: 'Vince Camuto',
  VC2: 'Vince Camuto',
  VIF: 'Vince Camuto Plus',
  V20: 'Vingino',
  VIO: 'Vintage Supply',
  VM4: 'Violeta by Mango',
  VII: 'Vita Liberata',
  VIG: 'Vitaly',
  VIS: 'Vitruvian man',
  VIQ: 'Vivetta',
  VIVI: 'Vivienne Westwood',
  VW9: 'Vivienne Westwood',
  VW6: 'Vivienne Westwood Anglomania',
  '1VG': 'VOGUE Eyewear',
  V19: 'Volcom',
  VO7: 'Volé la lumière',
  VD1: 'Von Dutch',
  V17: 'Vossen',
  VO8: 'Votary',
  VE4: 'VSP',
  WAB: 'Wacoal',
  WA01: 'Wal G',
  WAD: 'WAL G PETITE',
  WAH: 'WAL G TALL',
  WG0: 'WAL G.',
  WAL: 'WALD',
  W02: 'Walk London',
  WAG: 'Walkiddy',
  WA00: 'Wallis',
  WL5: 'Wallis',
  WP0: 'Wallis Petite',
  WAF: 'Wallis Tall',
  WAI: 'Wallis Wide Fit',
  WAE: 'Walnut',
  WC3: 'watercult',
  BAS: 'WAUW CAPOW by Bangbang Copenhagen',
  WAJ: 'WAWWA',
  WAC: 'WAY OUT LONDON',
  WEA: 'We are Cph',
  HOB: 'We are HAH',
  WEF: 'We are Kindred',
  WF5: 'WE Fashion',
  WEH: 'Wednesday\'s Girl',
  WEB: 'Weekday',
  W01: 'Weekend by Pedro Miralles',
  MW7: 'WEEKEND MaxMara',
  WE7: 'Weleda',
  WEE: 'Wella EIMI',
  WM1: 'Wemoto',
  WE1: 'WeSC',
  WHD: 'Whamisa',
  WHA: 'Wheat',
  WH0: 'Whistles',
  WH9: 'White Stuff',
  WHF: 'Who What Wear',
  WHC: 'WHY7',
  WIA: 'Wild Feet',
  WIK: 'Wild For The Weekend',
  WIC: 'Wildwuchs Bartpflege',
  WIH: 'Wilkinson Sword',
  WI2: 'Wilson',
  WI7: 'Windle & Moodie',
  WO8: 'Woden',
  WOC: 'Wolf & Whistle',
  WS5: 'Women Secret',
  WO3: 'Won Hundred',
  '1WB': 'Wonderbra',
  WO00: 'Wonders',
  WN1: 'WONDERS',
  WOF: 'Wonders Green',
  WO4: 'Wood Wood',
  WOD: 'Woodbird',
  WOJ: 'Wool & Co',
  WR1: 'Wrangler',
  WR9: 'Wrangler Plus',
  WR8: 'WRSTBHVR',
  XD1: 'XD Design',
  XT1: 'XTI',
  YA8: 'Yan Neo London',
  YA3: 'Yargici',
  YA00: 'YAS',
  Y01: 'YAS',
  YA5: 'YAS Petite',
  YA0: 'YAS Tall',
  YE1: 'Yellow Cab',
  YEC: 'Yes To',
  YO4: 'YMC You Must Create',
  YO7: 'YOGA CURVES',
  YO3: 'Yogasearcher',
  YO8: 'YOU & OIL',
  YO1: 'YOURTURN',
  ZZ1: 'ZAC Zac Posen',
  Z21: 'Zadig & Voltaire',
  ZZG: 'Zalando',
  ZAES: 'Zalando Essentials',
  ZA8: 'Zalando Essentials',
  ZX1: 'Zalando Essentials Curvy',
  ZX0: 'Zalando Essentials Maternity',
  ZAC: 'Zalando Essentials Tall',
  ZAG: 'ZARKOPERFUME',
  ZAI: 'ZAY',
  ZED: 'Zew for Men',
  Z10: 'Ziener',
  ZI9: 'ZIGGY Denim',
  ZIGN: 'Zign',
  ZI1: 'Zign',
  ZIB: 'Zign Curvy',
  ZIC: 'Zign Maternity',
  ZID: 'Zign Petite',
  ZIA: 'Zign Tall',
  ZIF: 'ZIGN Wide Fit',
  ZS4: 'Zimtstern',
  ZI7: 'Zip and Zoe',
  ZIE: 'Ziq and Yoni',
  ZI00: 'Zizzi',
  Z17: 'Zizzi',
  ZOA: 'Zoe Leggings',
  ZG1: 'Zoggs',
  ZOB: 'ZOË AYLA',
  ZW1: 'Zwilling',
  A1I: 'ÁNGEL ALARCÓN',
  ETE: 'Ética',
  ETF: 'Études',
  '47B': '\'47',
  L19: '120% Lino',
  S38: '2nd Day',
  PO9: '3 Pommes',
  '3I0': '3ina',
  '3X0': '3x1',
  '4F0': '4F',
  '4T0': '4th & Reckless',
  '4T1': '4th & Reckless Petite',
  '4T00': '4th Reckless',
  '7F1': '7 for all mankind',
  '9F0': '9Fashion',
  '9N0': '9N1M SENSE'
};
